version: '3.3'
services: 
    db:
        container_name: ${PROJECT_NAME}_db
        image: postgres:11.3-alpine
        env_file:
            - .env
    backend:
        container_name: ${PROJECT_NAME}_backend
        build: ./backend
        command: sh runserver.sh
        volumes: 
            - ./backend:/backend
        ports: 
            - 8000:8000
        env_file: 
            - .env